version: 2
jobs:
  build:
    environment:
      GO111MODULE: "on"
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/alecthomas/chroma
    steps:
      - checkout
      - run:
          name: Prepare
          command: |
            curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s v1.26.0
            mkdir ~/report
          when: always
      - run:
          name: Test
          command: |
            go test -v ./...
      - run:
          name: Lint
          command: |
            go build ./...
            ./bin/golangci-lint run
      - run:
          name: Release
          command: |
            curl -sL https://git.io/goreleaser | bash && goreleaser
